function [Name, partitionLine] = angleName(No)
Name={};
%     allNames = {'ank1+' ,'ank1-', 'ank2+', 'ank2-', 'knee+','knee-' ...
%                 'hip1+','hip1-', 'hip2+','hip2-', 'hip3+' ,'hip3-',...
%                 'pelv1+','pelv1-', 'pelv2+','pelv2-', 'pelv3+' ,'pelv3-',...
%                 'ank1' ,'ank2', 'knee', 'hip1', 'hip2','hip3', 'pelv1', 'pelv2','pelv3'};
    allNames = {'A/DF','A/PF','A/Inv','A/Evr','K/Flx','K/Ext',...
                 'H/Flx','H/Ext','H/Add','H/Abd','H/IR','H/ER',...
                 'P/PT', 'P/AT', 'P/LO','P/RO','P/IR','P/IR',...
                  'A/DF/PF','A/Inv/Evr','K/Flx/Ext','H/Flx/Ext','H/Add/Abd','H/IR/ER','P/PT/AT','P/LO/RO', 'P/IR/ER'};
    allNo = {'1' ,'2', '3', '4', '5','6', ...
            '7','8', '9','10', '11' ,'12',...
            '13','14', '15','16', '17' ,'18',...
            '19','20', '21','22', '23' ,'24','25', '26' ,'27'};
for i=1:length(No)
    id = find(ismember(allNo,num2str(No(i))));    
    Name{i} = allNames{id(1)};
end
partitionLine = [4.5 6.5 12.5];



